# Generated by Django 3.2.4 on 2023-09-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('product_picture', models.CharField(max_length=300, null=True)),
                ('pw', models.FloatField(null=True)),
                ('added_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='product_pic',
            field=models.ImageField(null=True, upload_to='static/product/'),
        ),
    ]
